version: "3"

services:
  citus-master:
    container_name: citus_master
    image: "citusdata/citus:12.0.0"
    ports:
      - "5432:5432"
    labels: ["com.citusdata.role=Master"]
    environment:
      POSTGRES_DB: "otusdb"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpassword"
      PGUSER: "dbuser"
      PGPASSWORD: "dbpassword"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - otus-network
    # volumes:
    #   - ./postgres:/docker-entrypoint-initdb.d
  citus-worker:
    container_name: citus_worker
    image: "citusdata/citus:12.0.0"
    labels: ["com.citusdata.role=Worker"]
    depends_on:
      - citus-manager
    environment:
      POSTGRES_DB: "otusdb"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpassword"
      PGUSER: "dbuser"
      PGPASSWORD: "dbpassword"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    command: "./postgres/wait-for-manager.sh"
    volumes:
      - ./volumes/healthcheck-volume:/healthcheck
    networks:
      - otus-network
  citus-manager:
    container_name: citus_manager
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./volumes/healthcheck-volume:/healthcheck
    depends_on:
      - citus-master
    environment:
      POSTGRES_DB: "otusdb"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpassword"
      PGUSER: "dbuser"
      PGPASSWORD: "dbpassword"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - otus-network

networks:
  otus-network:
    name: otus-network
    driver: bridge