global:
  scrape_interval: 10s
  scrape_timeout: 5s

rule_files:

scrape_configs:
  - job_name: 'otus-api-1'
    static_configs:
      - targets: ['otus-api-1:5001']
  - job_name: 'otus-api-2'
    static_configs:
      - targets: ['otus-api-2:5002']
  - job_name: 'otus-api-3'
    static_configs:
      - targets: ['otus-api-3:5003']