version: '2'
services:
  rabbitmq1:
    image: docker.io/bitnami/rabbitmq:3.12
    container_name: rabbitmq1
    hostname: rabbitmq1
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=bitnami
      - RABBITMQ_NODE_TYPE=stats
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq1
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
    ports:
      - 5681:5672
      - 15681:15672
    volumes:
      - 'rabbitmqstats_data:/bitnami/rabbitmq/mnesia'
  rabbitmq2:
    image: docker.io/bitnami/rabbitmq:3.12
    container_name: rabbitmq2
    hostname: rabbitmq2
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=bitnami
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq2
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@rabbitmq1
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
    volumes:
      - 'rabbitmqdisc1_data:/bitnami/rabbitmq/mnesia'
    ports:
      - 5682:5672
      - 15682:15672
  rabbitmq3:
    image: docker.io/bitnami/rabbitmq:3.12
    container_name: rabbitmq3
    hostname: rabbitmq3
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=bitnami
      - RABBITMQ_NODE_TYPE=queue-ram
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq3
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@rabbitmq1
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
    volumes:
      - 'rabbitmqram1_data:/bitnami/rabbitmq/mnesia'
    ports:
      - 5683:5672
      - 15683:15672
  haproxy:
      image: haproxy:1.7
      volumes:
        - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      depends_on:
        - rabbitmq1
        - rabbitmq2
        - rabbitmq3
      ports:
        - 15672:15672
        - 5672:5672
        - 1936:1936
volumes:
  rabbitmqstats_data:
    driver: local
  rabbitmqdisc1_data:
    driver: local
  rabbitmqram1_data:
    driver: local